@startuml test


class Product {
    + name : String
    + price : double
}

DiscountCalculator "1" *- "many" Product

class DiscountCalculator {
    + products : ArrayList<Product>
    ----
    + discountByPercentage(minimumPrice : double, percentage: double) : void
    + addFreeCompanyGlass(minimumPrice : double, percentage: double) : void
    + threeForPriceOfTwo(minimumPrice : double, percentage: double) : void
}

@enduml